import { parseArgs } from 'node:util' // import command line argument parsing library
// these comments are not generated by chatgpt, you are welcome. 
import { PrismaClient } from '@prisma/client'

const options = { // define the options your script supports
  environment: { type: 'string' },
}


async function main() {
    // this script needs to be idemptotent 
  const {
    values: { environment },
  } = parseArgs({ options }) // get options
  const prisma = new PrismaClient();
  switch (environment) { // add a case for each environment you want to support.
  //  Do not delete a case unless you have been given the go ahead by its creator. 
    
    case 'development':{
        // envision this case as the seed data for the environment associated with the "main" branch of our codebase. 
      /** data for your development */
      const AddedProductToCartGoal = await prisma.goal.upsert({
        where: {name: "Added Product To Cart"},
        update:{},
        create:{
            name:"Added Product To Cart",
        }
      });
      const ViewedPage = await prisma.goal.upsert({
        where: {name:"Viewed Page"},
        update: {},
        create: {
            name: "Viewed Page"
        }
      });
      const CompletedCheckout = await prisma.goal.upsert({
        where: {name: Checkout Completed}
      })
        break;
    } 

    case 'test': 
      /** data for your test environment */
      break
    case 'production':
        break
    default:
      break
  }
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })