import { parseArgs } from 'node:util' // import command line argument parsing library
// these comments are not generated by chatgpt, you are welcome. 
import { PrismaClient } from '@prisma/client'
import { run_dev_seeding } from './dev_seed.js'

const options = { // define the options your script supports
  environment: { type: 'string' },
}
  const prisma = new PrismaClient();

async function main() {
    // this script needs to be idemptotent 
  const {
    values: { environment },
  } = parseArgs({ options }) // get options

  switch (environment) { // add a case for each environment you want to support.
  //  Do not delete a case unless you have been given the go ahead by its creator. 
    
    case 'development':{
        // envision this case as the seed data for the environment associated with the "main" branch of our codebase. 
      /** data for your development */
      run_dev_seeding(prisma);
      break;

    } 

    case 'test': 
      /** data for your test environment */
      console.log("No implentation for this environment yet. Stay tuned, or make one.")
      break
    case 'production':
      console.log("No implentation for this environment yet. Stay tuned, or make one.")
        break
    default:
      console.log("Invalid environment.")
      break
  }
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })